# Generated by Django 5.2.5 on 2025-09-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("author", models.CharField(blank=True, max_length=120)),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="libros_covers/"
                    ),
                ),
                (
                    "summary",
                    models.CharField(max_length=220, verbose_name="Resumen corto"),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=4000, verbose_name="Descripción / reseña"
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="Palabras clave (coma)"
                    ),
                ),
                ("pages", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "published_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha publicación"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Destacado"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
