# Generated by Django 5.2.5 on 2025-09-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="book",
            field=models.FileField(blank=True, null=True, upload_to="libros_files/"),
        ),
    ]
