# Generated by Django 5.2.5 on 2025-09-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libros", "0002_libro_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="libro",
            name="book",
        ),
    ]
