# Generated by Django 5.2.5 on 2025-09-03 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="link_imagen",
            new_name="imagen",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="activo",
        ),
    ]
